site_name: BlindFriendly
site_url: https://blindfriendly.ru/
site_description: Каталог сервисов и приложений для слепых и слабовидящих
site_author: kirshmelev
repo_url: https://github.com/kirshmelev/blindfriendly.ru/
edit_uri_template: 'https://github.com/kirshmelev/blindfriendly.ru/edit/main/docs/{path}'
theme:
  locale: ru
  features:
    - navigation.instant
    - header.autohide
  name: bootstrap
copyright: '&copy; 2024, Шмелев Кирилл Андреевич <br/>Сайт создан и поддерживается <a href="https://kirshmelev.ru/">Кириллом Шмелевым</a> при поддержке проекта <a href="https://vk.com/mirnezryachih">Мир Незрячих</a> и неравнодушных людей'